const AddFieldOperators = () => {
    return (
        <section className="w-full py-10">
            <div className="custom-container space-y-5">
                <div className="w-full">
                    <h2 className="mb-5 text-green-800 font-semibold text-2xl">
                        Data Transformation & Conditional Operators
                    </h2>
                    <p className="pl-5 mb-2">
                        MongoDB aggregation pipelines provide stages like <span className="font-semibold text-green-600">$addFields</span> and <span className="font-semibold text-green-600">$project</span> along with expressions like <span className="font-semibold text-green-600">$cond</span>, <span className="font-semibold text-green-600">$ifNull</span>, and <span className="font-semibold text-green-600">$switch</span> to modify document structures and evaluate complex logic.
                    </p>
                    <p className="pl-5 mb-5">
                        Let's imagine we have this <span className="font-semibold text-green-600">students</span> collection:
                    </p>

                    <pre className="code-block mb-5 custom-scroll">
                        <code>{`
    [
      {
        "id": 1,
        "firstName": "Arjun",
        "lastName": "Rao",
        "marks": [65, 22, 58],
        "city": "Chennai"
      },
      {
        "id": 2,
        "firstName": "Karthik",
        "lastName": "Menon",
        "marks": [78, 69, 82],
        "city": "Bengaluru"
      },
      {
        "id": 3,
        "firstName": "Divya",
        "lastName": "Sharma",
        "marks": [85, 70, 76],
        "city": null
      },
      {
        "id": 4,
        "firstName": "Vignesh",
        "lastName": "Iyer",
        "marks": [55, 67, 63],
        "city": "Hyderabad"
      },
      {
        "id": 5,
        "firstName": "Priya",
        "lastName": "Nair",
        "marks": [73, 68, 71]
      }
    ]
        `}</code>
                    </pre>
                </div>

                {/* 1. $addFields */}
                <div>
                    <h3 className="mb-5 text-green-800 font-semibold text-xl">
                        1. Adding New Fields with $addFields
                    </h3>
                    <p className="pl-5 mb-5">
                        The <span className="font-semibold text-green-600">$addFields</span> stage adds new fields to documents while keeping all existing fields intact.
                    </p>

                    <pre className="code-block mb-5 custom-scroll">
                        <code>{`
    db.students.aggregate([
      {
        $addFields: {
          fullName: { $concat: ["$firstName", " ", "$lastName"] }
        }
      }
    ])
        `}</code>
                    </pre>

                    <p className="pl-5 mb-5">
                        Here, a new field named <span className="text-sm text-green-600 font-semibold">fullName</span> is generated by concatenating <span className="text-sm text-green-600 font-semibold">firstName</span> and <span className="text-sm text-green-600 font-semibold">lastName</span>, leaving all original fields in place.
                    </p>
                </div>

                {/* 2. $addFields with $$REMOVE */}
                <div>
                    <h3 className="mb-5 text-green-800 font-semibold text-xl">
                        2. Removing Fields using $$REMOVE in $addFields
                    </h3>
                    <p className="pl-5 mb-5">
                        Setting a field's value to the built-in system variable <span className="font-semibold text-green-600">"$$REMOVE"</span> inside <span className="font-semibold text-green-600">$addFields</span> strips that field from the output documents.
                    </p>

                    <pre className="code-block mb-5 custom-scroll">
                        <code>{`
    db.students.aggregate([
      {
        $addFields: {
          fullName: { $concat: ["$firstName", " ", "$lastName"] },
          firstName: "$$REMOVE",
          lastName: "$$REMOVE"
        }
      }
    ])
        `}</code>
                    </pre>

                    <p className="pl-5 mb-5">
                        Here, <span className="text-sm text-green-600 font-semibold">fullName</span> is created while <span className="text-sm text-green-600 font-semibold">firstName</span> and <span className="text-sm text-green-600 font-semibold">lastName</span> are discarded from the output.
                    </p>
                </div>

                {/* 3. $project */}
                <div>
                    <h3 className="mb-5 text-green-800 font-semibold text-xl">
                        3. Shaping Output with $project
                    </h3>
                    <p className="pl-5 mb-5">
                        Unlike <span className="font-semibold text-green-600">$addFields</span>, the <span className="font-semibold text-green-600">$project</span> stage reshapes documents by explicitly specifying which fields to include, exclude, or dynamically compute.
                    </p>

                    <pre className="code-block mb-5 custom-scroll">
                        <code>{`
    db.students.aggregate([
      {
        $project: {
          fullName: { $concat: ["$firstName", " ", "$lastName"] },
          _id: 0
        }
      }
    ])
        `}</code>
                    </pre>

                    <p className="pl-5 mb-5">
                        Here, only <span className="text-sm text-green-600 font-semibold">fullName</span> is returned while <span className="text-sm text-green-600 font-semibold">_id: 0</span> explicitly hides the document identifier. All other fields are dropped by default.
                    </p>
                </div>

                {/* 4. $ifNull */}
                <div>
                    <h3 className="mb-5 text-green-800 font-semibold text-xl">
                        4. Handling Missing or Null Values with $ifNull
                    </h3>
                    <p className="pl-5 mb-5">
                        The <span className="font-semibold text-green-600">$ifNull</span> expression evaluates an input expression and returns a replacement value (or removes the field using <span className="font-semibold text-green-600">"$$REMOVE"</span>) if the field is missing or null.
                    </p>

                    <pre className="code-block mb-5 custom-scroll">
                        <code>{`
    db.students.aggregate([
      {
        $addFields: {
          fullName: { $concat: ["$firstName", " ", "$lastName"] },
          firstName: "$$REMOVE",
          lastName: "$$REMOVE",
          city: {
            $ifNull: ["$city", "$$REMOVE"]
          }
        }
      }
    ])
        `}</code>
                    </pre>

                    <p className="pl-5 mb-5">
                        Here, if <span className="text-sm text-green-600 font-semibold">city</span> is null or missing (like in Divya or Priya's record), <span className="text-sm text-green-600 font-semibold">$ifNull</span> evaluates to <span className="text-sm text-green-600 font-semibold">"$$REMOVE"</span>, completely removing the key from the output document.
                    </p>
                </div>

                {/* 5. $cond */}
                <div>
                    <h3 className="mb-5 text-green-800 font-semibold text-xl">
                        5. Conditional Field Logic with $cond
                    </h3>
                    <p className="pl-5 mb-5">
                        The <span className="font-semibold text-green-600">$cond</span> operator evaluates a boolean expression and returns one of two specified outcomes depending on whether the condition is true or false.
                    </p>

                    <pre className="code-block mb-5 custom-scroll">
                        <code>{`
    db.students.aggregate([
      {
        $addFields: {
          fullName: { $concat: ["$firstName", " ", "$lastName"] },
          firstName: "$$REMOVE",
          lastName: "$$REMOVE",
          city: {
            $cond: {
              if: { $eq: ["$city", "Chennai"] },
              then: "$$REMOVE",
              else: "$city"
            }
          }
        }
      }
    ])
        `}</code>
                    </pre>

                    <p className="pl-5 mb-5">
                        Here, if <span className="text-sm text-green-600 font-semibold">city</span> equals "Chennai", <span className="text-sm text-green-600 font-semibold">$cond</span> removes the city field; otherwise, it keeps the original city value.
                    </p>
                </div>

                {/* 6. Advanced Pipeline */}
                <div>
                    <h3 className="mb-5 text-green-800 font-semibold text-xl">
                        6. Complex Logic with $allElementsTrue, $map, and $switch
                    </h3>
                    <p className="pl-5 mb-5">
                        By combining <span className="font-semibold text-green-600">$map</span>, <span className="font-semibold text-green-600">$allElementsTrue</span>, and <span className="font-semibold text-green-600">$switch</span>, you can perform advanced array evaluations and multi-branch condition checks.
                    </p>

                    <pre className="code-block mb-5 custom-scroll">
                        <code>{`
    db.students.aggregate([
      {
        $addFields: {
          fullName: { $concat: ["$firstName", " ", "$lastName"] },
          totalMarks: { $sum: "$marks" },
          averageMarks: { $avg: "$marks" },
          result: {
            $cond: {
              if: {
                $allElementsTrue: {
                  $map: {
                    input: "$marks",
                    as: "mark",
                    in: { $gt: ["$$mark", 34] }
                  }
                }
              },
              then: "Pass",
              else: "Fail"
            }
          },
          grade: {
            $cond: {
              if: {
                $allElementsTrue: {
                  $map: {
                    input: "$marks",
                    as: "mark",
                    in: { $gt: ["$$mark", 34] }
                  }
                }
              },
              then: {
                $switch: {
                  branches: [
                    { case: { $gte: ["$averageMarks", 90] }, then: "A" },
                    { case: { $gte: ["$averageMarks", 80] }, then: "B" },
                    { case: { $gte: ["$averageMarks", 70] }, then: "C" },
                    { case: { $lt: ["$averageMarks", 70] }, then: "D" }
                  ],
                  default: "Invalid"
                }
              },
              else: "No Grade"
            }
          }
        }
      },
      {
        $project: {
          fullName: 1,
          marks: 1,
          totalMarks: 1,
          averageMarks: 1,
          result: 1,
          grade: 1,
          _id: 0
        }
      }
    ]);
        `}</code>
                    </pre>

                    <p className="pl-5 mb-5">
                        Here, <span className="text-sm text-green-600 font-semibold">$map</span> iterates over every score in the <span className="text-sm text-green-600 font-semibold">marks</span> array to check if each is greater than 34, and <span className="text-sm text-green-600 font-semibold">$allElementsTrue</span> ensures a student passes only if all subjects meet the passing mark. If passed, <span className="text-sm text-green-600 font-semibold">$switch</span> assigns a grade based on their <span className="text-sm text-green-600 font-semibold">averageMarks</span>.
                    </p>
                </div>
            </div>
        </section>
    );
};

export default AddFieldOperators;